version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Bryan_Cochrane_2017.pdf
    - images/*
    - styles/main.css
    - babel.html
